SELECT
    O_REC AS ANIMAL_ID,
    NAME
FROM
(
SELECT
    I.ANIMAL_ID AS I_REC,
    O.ANIMAL_ID AS O_REC,
    O.NAME
FROM
    ANIMAL_OUTS O
    LEFT OUTER JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
) A
WHERE A.I_REC IS NULL
ORDER BY ANIMAL_ID