SELECT
	EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
	EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
	GENDER,
	COUNT(DISTINCT S.USER_ID) AS USERS
FROM
	USER_INFO U, ONLINE_SALE S
WHERE
	U.USER_ID = S.USER_ID
	AND GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER