SELECT
	DISTINCT 
	C.CAR_ID,
	C.CAR_TYPE,
	ROUND(DAILY_FEE * 30 * (1-DISCOUNT_RATE/100)) AS FEE
FROM
	CAR_RENTAL_COMPANY_CAR C
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    ON C.CAR_ID = RH.CAR_ID
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON C.CAR_TYPE = DP.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
    	SELECT CAR_ID
    	FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    	WHERE '2022-11' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(END_DATE, 'YYYY-MM')
    )
    AND DURATION_TYPE = '30일 이상'
    AND DAILY_FEE * 30 * (1-DISCOUNT_RATE/100) >= 500000
    AND DAILY_FEE * 30 * (1-DISCOUNT_RATE/100) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC