SELECT
    A.FOOD_TYPE,
    REST_ID,
    REST_NAME,
    A.FAVORITES
FROM
(
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM
        REST_INFO
    GROUP BY FOOD_TYPE
) A,
REST_INFO B
WHERE
    A.FOOD_TYPE = B.FOOD_TYPE
    AND A.FAVORITES = B.FAVORITES
ORDER BY A.FOOD_TYPE DESC