-- SELECT
--     ANIMAL_ID
-- FROM
--     ANIMAL_INS
-- WHERE
--     SEX_UPON_INTAKE LIKE 'Intact%'

SELECT DISTINCT
    O.ANIMAL_ID,
    O.ANIMAL_TYPE,
    I.NAME    
FROM
    ANIMAL_INS I,
    ANIMAL_OUTS O
WHERE
    I.ANIMAL_ID = O.ANIMAL_ID
    AND SEX_UPON_INTAKE LIKE 'Intact%'
    AND (SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY 1