SELECT 
    USER_ID,
    NICKNAME,
    TOTAL_SALES
FROM
(
    SELECT 
        B.WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM
        USED_GOODS_BOARD B
    WHERE
        STATUS = 'DONE'
    GROUP BY B.WRITER_ID
) B,
USED_GOODS_USER U
WHERE
    B.WRITER_ID = U.USER_ID
    AND TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES