SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(PRICE*SALES) AS TOTAL_SALES
FROM
	BOOK B,
    BOOK_SALES BS,
    AUTHOR A
WHERE
	B.BOOK_ID = BS.BOOK_ID
	AND B.AUTHOR_ID = A.AUTHOR_ID
	AND SALES_DATE
    BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD')
    AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC