WITH BASE AS (
SELECT
    CAR_ID,
    '대여중' AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    TO_DATE('2022-10-16','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
)

SELECT
    DISTINCT
    A.CAR_ID,
    NVL(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    LEFT OUTER JOIN BASE B
    ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC