SELECT
    O.PRODUCT_ID,
    MAX(PRODUCT_NAME) AS PRODUCT_NAME,
    SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM
    FOOD_ORDER O
    INNER JOIN FOOD_PRODUCT P
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID